version: "3.9"

services:
  build:
    image: gtfs_container
    container_name: gtfs_container
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./share:/share
    command: ["tail", "-f", "/dev/null"]
