version: "3.9"

services:
  build:
    image: gtfs_container
    container_name: gtfs_container
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./share:/app/share
    command: ["tail", "-f", "/dev/null"]

  valid:
    image: gtfs_container
    volumes:
      - ./share:/app/share
    command: ["java", "-Xmx7G" , "-jar", "gtfs-validator.jar", "-p" ,"-i", "share/in.gtfs.zip", "-o" ,"share"]

  check:
    image: gtfs_container
    volumes:
      - ./share:/app/share
    command: ["gtfsPipeline", "-i", "share/report.json"]

  pipFile:
    image: gtfs_container
    volumes:
      - ./share:/app/share
      - ./config.json:/app/config.json
    command: ["gtfsPipeline", "-c", "config.json"]

  tidy:
    image: gtfs_container
    volumes:
      - ./share:/app/share
    command: ["java", "-Xmx7G" , "-jar", "oba-transformer.jar", "--transform=share/modifications.txt" , "share/in.gtfs.zip", "share/tidy.gtfs.zip"]

  otp-build:
    image: gtfs_container
    volumes:
      - ./share:/app/share
      - ./otp-config.json:/app/share/data/otp-config.json

    command: ["java", "-Xmx20G" , "-jar", "otp.jar", "--build" , "--save", "share/data"]
    #RUN java -Xmx8G -jar target/otp-2.5.0-shaded.jar  --build --save data 

  otp-start:
    image: gtfs_container
    volumes:
      - ./share:/app/share

    command: ["java", "-Xmx20G", "-jar", "otp-2.5.0-shaded.jar", "--load", "share/data"]
    #RUN java -Xmx8G -jar target/otp-2.5.0-shaded.jar  --build --save data 